# Generated by Django 3.2.5 on 2021-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='budgets',
            field=models.ManyToManyField(to='budget.Budget'),
        ),
    ]
