# Generated by Django 3.2.5 on 2021-08-22 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='budget.budget'),
        ),
    ]
