# Generated by Django 3.2.5 on 2021-07-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('waste_money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastemoney',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_money', to='budget.budget'),
        ),
    ]
