# Generated by Django 3.2.5 on 2021-07-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_money', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastemoney',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='waste_money', to='waste_money.category'),
            preserve_default=False,
        ),
    ]
