# Generated by Django 3.2.5 on 2021-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_money', '0004_wastemoney_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastemoney',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
